# Generated by Django 5.2.5 on 2025-08-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_game_image_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
