# Generated by Django 5.2.5 on 2025-08-20 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_game_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='image',
            new_name='image_filename',
        ),
    ]
