# Generated by Django 5.2.5 on 2025-08-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_platform_publisher_game_platforms_game_publisher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['title']},
        ),
    ]
