# Generated by Django 5.2.5 on 2025-08-29 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_game_genres_alter_game_publisher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platforms',
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('character_name', models.CharField(blank=True, max_length=120)),
                ('content', models.TextField()),
                ('image_filename', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wikis', to='reviews.game')),
            ],
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
