# Generated by Django 5.2.5 on 2025-08-30 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_remove_game_platforms_wiki_delete_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='wiki',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='reviews.wiki'),
        ),
    ]
